import type { FastifyInstance } from 'fastify';
import { appointmentRoute } from './routes/appointment.js';
import { authRoute } from './routes/auth.js';
import { classRoute } from './routes/class.js';
import { communityRoute } from './routes/community.js';
import { couponRoute } from './routes/coupon.js';
import { courseRoute } from './routes/course.js';
import { customerRoute } from './routes/customer.js';
import { doubtRoute } from './routes/doubt.js';
import { doubtChatRoute } from './routes/doubt-chat.js';
import { faqRoute } from './routes/faq.js';
import { forumRoute } from './routes/forum.js';
import { globalPromoLinkRoute } from './routes/global-promo-link.js';
import { lessonRoute } from './routes/lesson.js';
import { mercadoLivreOAuthRoute } from './routes/mercado-livre-oauth.js';
import { moduleRoute } from './routes/module.js';
import { paymentLinkRoute } from './routes/payment-link.js';
import { productRoute } from './routes/product.js';
import { progressRoute } from './routes/progress.js';
import { promoLinkRoute } from './routes/promo-link.js';
import { provisioningRoute } from './routes/provisioning.js';
import { purchaseRoute } from './routes/purchase.js';
import { quizRoute } from './routes/quiz.js';
import { savedLessonRoute } from './routes/saved-lesson.js';
import { systemClassRoute } from './routes/system-class.js';
import { userRoute } from './routes/user.js';
import { vectorRoute } from './routes/vector.js';
import { vectorLibraryRoute } from './routes/vector-library.js';
import { vectorSupportRoute } from './routes/vector-support.js';
import { webhookRoute } from './routes/webhook.js';

export const routes = async (app: FastifyInstance) => {
	app.register(webhookRoute);
	app.register(authRoute);
	app.register(appointmentRoute);
	app.register(classRoute);
	app.register(systemClassRoute);
	app.register(communityRoute);
	app.register(couponRoute);
	app.register(courseRoute);
	app.register(customerRoute);
	app.register(doubtChatRoute);
	app.register(doubtRoute);
	app.register(lessonRoute);
	app.register(moduleRoute);
	app.register(productRoute);
	app.register(paymentLinkRoute);
	app.register(promoLinkRoute);
	app.register(globalPromoLinkRoute);
	app.register(purchaseRoute);
	app.register(quizRoute);
	app.register(userRoute);
	app.register(progressRoute);
	app.register(savedLessonRoute);
	app.register(vectorRoute);
	app.register(vectorLibraryRoute);
	app.register(vectorSupportRoute);
	app.register(faqRoute);
	app.register(forumRoute);
	app.register(provisioningRoute);
	app.register(mercadoLivreOAuthRoute);
};
