import type { FastifyInstance } from 'fastify';
import { appointmentRoute } from './routes/appointment.js';
import { appointmentConfigRoute } from './routes/appointment-config.js';
import { authRoute } from './routes/auth.js';
import { classRoute } from './routes/class.js';
import { communityRoute } from './routes/community.js';
import { couponRoute } from './routes/coupon.js';
import { courseRoute } from './routes/course.js';
import { creditRoute } from './routes/credit.js';
import { customerRoute } from './routes/customer.js';
import { customerMachineRoute } from './routes/customer-machine.js';
import { designRoute } from './routes/design.js';
import { doubtRoute } from './routes/doubt.js';
import { doubtChatRoute } from './routes/doubt-chat.js';
import { editorAiRoute } from './routes/editor-ai.js';
import { faqRoute } from './routes/faq.js';
import { forumRoute } from './routes/forum.js';
import { globalPromoLinkRoute } from './routes/global-promo-link.js';
import { mlSellerRoute } from './routes/internal/ml-seller.js';
import { knowledgeBaseRoute } from './routes/knowledge-base.js';
import { laserProductRoute } from './routes/laser-product.js';
import { lessonRoute } from './routes/lesson.js';
import { machineRoute } from './routes/machine.js';
import { mercadoLivreOAuthRoute } from './routes/mercado-livre-oauth.js';
import { moduleRoute } from './routes/module.js';
import { parameterRoute } from './routes/parameter.js';
import { paymentLinkRoute } from './routes/payment-link.js';
import { previaRoute } from './routes/previa.js';
import { productRoute } from './routes/product.js';
import { productParameterRoute } from './routes/product-parameter.js';
import { progressRoute } from './routes/progress.js';
import { promoLinkRoute } from './routes/promo-link.js';
import { provisioningRoute } from './routes/provisioning.js';
import { purchaseRoute } from './routes/purchase.js';
import { quizRoute } from './routes/quiz.js';
import { savedLessonRoute } from './routes/saved-lesson.js';
import { systemClassRoute } from './routes/system-class.js';
import { templateRoute } from './routes/template.js';
import { userRoute } from './routes/user.js';
import { vectorRoute } from './routes/vector.js';
import { vectorLibraryRoute } from './routes/vector-library.js';
import { vectorSupportRoute } from './routes/vector-support.js';
import { vectorizeHelpRoute } from './routes/vectorize-help.js';
import { watermarkRoute } from './routes/watermark.js';
import { webhookRoute } from './routes/webhook.js';
import { mercadoLivreWebhookRoute } from './routes/webhooks/mercado-livre.js';

export const routes = async (app: FastifyInstance) => {
	app.register(webhookRoute);
	app.register(authRoute);
	app.register(appointmentRoute);
	app.register(appointmentConfigRoute);
	app.register(classRoute);
	app.register(systemClassRoute);
	app.register(communityRoute);
	app.register(couponRoute);
	app.register(courseRoute);
	app.register(creditRoute);
	app.register(customerRoute);
	app.register(doubtChatRoute);
	app.register(doubtRoute);
	app.register(knowledgeBaseRoute);
	app.register(lessonRoute);
	app.register(moduleRoute);
	app.register(productRoute);
	app.register(parameterRoute);
	app.register(paymentLinkRoute);
	app.register(previaRoute);
	app.register(promoLinkRoute);
	app.register(globalPromoLinkRoute);
	app.register(purchaseRoute);
	app.register(quizRoute);
	app.register(userRoute);
	app.register(progressRoute);
	app.register(savedLessonRoute);
	app.register(vectorRoute);
	app.register(vectorLibraryRoute);
	app.register(vectorSupportRoute);
	app.register(faqRoute);
	app.register(forumRoute);
	app.register(templateRoute);
	app.register(designRoute);
	app.register(laserProductRoute);
	app.register(watermarkRoute);
	app.register(vectorizeHelpRoute);
	app.register(machineRoute);
	app.register(customerMachineRoute);
	app.register(productParameterRoute);
	app.register(editorAiRoute);
	app.register(provisioningRoute);
	app.register(mercadoLivreOAuthRoute);
	app.register(mercadoLivreWebhookRoute);
	app.register(mlSellerRoute);
};
