import type { FastifyInstance } from 'fastify';
import { appointmentRoute } from './routes/appointment.js';
import { appointmentConfigRoute } from './routes/appointment-config.js';
import { communityRoute } from './routes/community.js';
import { couponRoute } from './routes/coupon.js';
import { customerRoute } from './routes/customer.js';
import { customerMachineRoute } from './routes/customer-machine.js';
import { designRoute } from './routes/design.js';
import { doubtRoute } from './routes/doubt.js';
import { doubtChatRoute } from './routes/doubt-chat.js';
import { editorAiRoute } from './routes/editor-ai.js';
import { faqRoute } from './routes/faq.js';
import { fornecedorRoute } from './routes/fornecedor.js';
import { forumRoute } from './routes/forum.js';
import { gamificationRoute } from './routes/gamification.js';
import { globalPromoLinkRoute } from './routes/global-promo-link.js';
import { healthRoute } from './routes/health.js';
import { imageModelsRoute } from './routes/image-models.js';
import { imageSizePresetRoute } from './routes/image-size-preset.js';
import { imageStudioRoute } from './routes/image-studio.js';
import { mlSellerRoute } from './routes/internal/ml-seller.js';
import { knowledgeBaseRoute } from './routes/knowledge-base.js';
import { laserLineTypeRoute } from './routes/laser-line-type.js';
import { laserProductRoute } from './routes/laser-product.js';
import { lessonRoute } from './routes/lesson.js';
import { licensedArtRoute } from './routes/licensed-art.js';
import { licensedBrandRoute } from './routes/licensed-brand.js';
import { licensedSellerRoute } from './routes/licensed-seller.js';
import { machineRoute } from './routes/machine.js';
import { mentorshipRoute } from './routes/mentorship.js';
import { mercadoLivreOAuthRoute } from './routes/mercado-livre-oauth.js';
import { moduleRoute } from './routes/module.js';
import { parameterRoute } from './routes/parameter.js';
import { paymentLinkRoute } from './routes/payment-link.js';
import { previaRoute } from './routes/previa.js';
import { productRoute } from './routes/product.js';
import { productParameterRoute } from './routes/product-parameter.js';
import { progressRoute } from './routes/progress.js';
import { promoLinkRoute } from './routes/promo-link.js';
import { provisioningRoute } from './routes/provisioning.js';
import { publicQuoteRoute } from './routes/public-quote.js';
import { purchaseRoute } from './routes/purchase.js';
import { quizRoute } from './routes/quiz.js';
import { quoteProfileRoutes } from './routes/quote-profile.js';
import { roleRoute } from './routes/role.js';
import { savedLessonRoute } from './routes/saved-lesson.js';
import { supportChatRoute } from './routes/support-chat.js';
import { templateRoute } from './routes/template.js';
import { textModelsRoute } from './routes/text-models.js';
import { toolAgentRoute } from './routes/tool-agent.js';
import { toolBankRoute } from './routes/tool-bank.js';
import { toolBankSmartTemaRoute } from './routes/tool-bank-smart-tema.js';
import { toolBankSummarizePromptRoute } from './routes/tool-bank-summarize-prompt.js';
import { toolCollectionRoute } from './routes/tool-collection.js';
import { toolRunRoute } from './routes/tool-run.js';
import { userRoute } from './routes/user.js';
import { vectorRoute } from './routes/vector.js';
import { vectorLibraryRoute } from './routes/vector-library.js';
import { vectorSupportRoute } from './routes/vector-support.js';
import { vectorizeHelpRoute } from './routes/vectorize-help.js';
import { watermarkRoute } from './routes/watermark.js';
import { webhookRoute } from './routes/webhook.js';
import { mercadoLivreWebhookRoute } from './routes/webhooks/mercado-livre.js';

export const routes = async (app: FastifyInstance) => {
	app.register(healthRoute);
	app.register(webhookRoute);
	app.register(appointmentRoute);
	app.register(appointmentConfigRoute);
	app.register(communityRoute);
	app.register(mentorshipRoute);
	app.register(couponRoute);
	app.register(customerRoute);
	app.register(doubtChatRoute);
	app.register(supportChatRoute);
	app.register(doubtRoute);
	app.register(knowledgeBaseRoute);
	app.register(lessonRoute);
	app.register(moduleRoute);
	app.register(productRoute);
	app.register(parameterRoute);
	app.register(laserLineTypeRoute);
	app.register(paymentLinkRoute);
	app.register(previaRoute);
	app.register(promoLinkRoute);
	app.register(globalPromoLinkRoute);
	app.register(publicQuoteRoute);
	app.register(purchaseRoute);
	app.register(quizRoute);
	app.register(roleRoute);
	app.register(userRoute);
	app.register(progressRoute);
	app.register(savedLessonRoute);
	app.register(vectorRoute);
	app.register(toolRunRoute);
	app.register(imageModelsRoute);
	app.register(imageSizePresetRoute);
	app.register(imageStudioRoute);
	app.register(textModelsRoute);
	app.register(toolAgentRoute);
	app.register(toolBankRoute);
	app.register(licensedArtRoute);
	app.register(licensedBrandRoute);
	app.register(licensedSellerRoute);
	app.register(toolCollectionRoute);
	app.register(toolBankSmartTemaRoute);
	app.register(toolBankSummarizePromptRoute);
	// Perfil curto do Orçamento: seis perguntas → os 31 campos. Não cobra, não
	// grava e não chama modelo — é cadastro, não cotação.
	app.register(quoteProfileRoutes);
	app.register(vectorLibraryRoute);
	app.register(vectorSupportRoute);
	app.register(faqRoute);
	app.register(fornecedorRoute);
	app.register(forumRoute);
	app.register(gamificationRoute);
	app.register(templateRoute);
	app.register(designRoute);
	app.register(laserProductRoute);
	app.register(watermarkRoute);
	app.register(vectorizeHelpRoute);
	app.register(machineRoute);
	app.register(customerMachineRoute);
	app.register(productParameterRoute);
	app.register(editorAiRoute);
	app.register(provisioningRoute);
	app.register(mercadoLivreOAuthRoute);
	app.register(mercadoLivreWebhookRoute);
	app.register(mlSellerRoute);
};
